apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: ruff
  title: Ruff
  description: Configure Ruff on an existing project.
  tags:
    - python
spec:
  owner: it-reaktion
  type: ci
  parameters:
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
            allowedOwners:
              - radiorabe
            requestUserCredentials:
              secretsKey: USER_GITHUB_OAUTH_TOKEN
              additionalScopes:
                github:
                  - workflow
  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ../../scaffolder-skeletons/ruff/
        replace: true
        values:
          actions_version: ${{ steps.getversion.output.body.tag_name }}
    - id: publish
      name: Publish
      action: publish:github:pull-request
      input:
        title: "chore(ci): configure ruff"
        token: ${{ secrets.USER_GITHUB_OAUTH_TOKEN }}
        repoUrl: ${{ parameters.repoUrl }}
        branchName: chore/ci/ruff
        update: true
        description: |
          # Configure [ruff](https://docs.astral.sh/ruff/)

          This configuration reflects the default RaBe Ruff config.

          Please check the following before you merge it:

          * [ ] pytest-ruff is installed and the `--ruff` arg is passed in `pyproject.toml`
          * [ ] `pyproject.toml` does not contain any further ruff configuration
  output:
    links:
      - url: ${{steps.publish.output.remoteUrl}}
        title: "Go to PR"
