apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: dependabot
  title: Dependabot
  description: Enable Dependabot on an existing project.
  tags:
    - recommended
spec:
  owner: it-reaktion
  type: ci
  parameters:
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
            allowedOwners:
              - radiorabe
            requestUserCredentials:
              secretsKey: USER_GITHUB_OAUTH_TOKEN
    - title: Enable Ecosystems
      required:
        - ecosystems
      properties:
        ecosystems:
          title: Select ecosystems
          type: array
          items:
            type: string
            enum:
              - 'Enable Docker'
              - 'Enable Python'
              - 'Enable GitHub Actions'
          uniqueItems: true
          ui:widget: checkboxes
  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ../../scaffolder-skeletons/dependabot/
        replace: true
        values:
          is_docker: ${{ parameters.ecosystems.includes('Enable Docker') }}
          is_python: ${{ parameters.ecosystems.includes('Enable Python') }}
          is_github_actions: ${{ parameters.ecosystems.includes('Enable GitHub Actions') }}
    - id: publish
      name: Publish
      action: publish:github:pull-request
      input:
        title: "chore(ci): configure dependabot"
        token: ${{ secrets.USER_GITHUB_OAUTH_TOKEN }}
        repoUrl: ${{ parameters.repoUrl }}
        branchName: chore/ci/dependabot
        update: true
        description: |
          # Initialize [GitHub Dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/about-dependabot-security-updates).

          Configures Dependabot to create regular update PRs.
  output:
    links:
      - url: ${{steps.publish.output.remoteUrl}}
        title: "Go to PR"
