name: Semantic Release

on:
  push:
    branches:
      - main
      - release/*

jobs:
  semantic-release:
    uses: radiorabe/actions/.github/workflows/semantic-release.yaml@
    secrets:
      RABE_ITREAKTION_GITHUB_TOKEN: {{ '' }}
